{
 "title": "Gimbal Discovery",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Namespace", "query": "label_values(namespace)" },
   { "name": "BackendCluster", "query": "label_values(clustername)" }
  ]
 },
 "panels": [
  {
   "title": "Total Services Discovered",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(gimbal_service_event_timestamp{namespace=~\"$Namespace\",clustername=~\"$BackendCluster\"})"
    }
   ]
  },
  {
   "title": "Total Endpoints Discovered",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(gimbal_endpoints_event_timestamp{namespace=~\"$Namespace\",clustername=~\"$BackendCluster\"})"
    }
   ]
  },
  {
   "title": "Discovery Errors per Backend Cluster",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gimbal_service_error_total{namespace=~\"$Namespace\",clustername=~\"$BackendCluster\"}) by (clustername)",
     "legendFormat": "Service errors: {{clustername}}"
    },
    {
     "expr": "sum(gimbal_endpoints_error_total{namespace=~\"$Namespace\",clustername=~\"$BackendCluster\"}) by (clustername)",
     "legendFormat": "Service errors: {{clustername}}"
    }
   ]
  },
  {
   "title": "Discovery Errors per Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gimbal_service_error_total{namespace=~\"$Namespace\",clustername=~\"$BackendCluster\"}) by (namespace)",
     "legendFormat": "Service errors: {{namespace}}"
    },
    {
     "expr": "sum(gimbal_endpoints_error_total{namespace=~\"$Namespace\",clustername=~\"$BackendCluster\"}) by (namespace)",
     "legendFormat": "Endpoints errors: {{namespace}}"
    },
    {}
   ]
  }
 ]
}